### ISSUE TITLE
The dispatcher version in the container is out-of-sync from master

### ISSUE THREAD

**Issue by dsavchenko** [oda-hub/dispatcher-container#17]
Probably, other parts as well. 
Submodules are updated somehow externally, right?

**Comment by volodymyrss** [comment]
yeah. I will now update manually and push, and we should do like in frontend to avoid integration by bot https://github.com/oda-hub/dispatcher-container/issues/18

**Comment by dsavchenko** [comment]
There is a [failure](https://github.com/oda-hub/dispatcher-container/actions/runs/11285253698/job/31398466104) with the new approach that I don't quite understand...
Any ideas?

**Comment by volodymyrss** [comment]
Apparently `oda_api` version in submodule reference could not be merged with master.
Fixing it works, but its safer to just force [master](https://github.com/oda-hub/dispatcher-container/commit/f1fd349fd518194f5021872ab796ffc1b716fcea).
By the way, we are not updating dispatcher container repository here, but it's sort of ok since the timestamp defines image tag.
Would be better to commit and push after checkout.

**Comment by volodymyrss** [comment]
I see new version is already deployed. Please reopen this issue if something still out of sync.

**Comment by dsavchenko** [comment]
> Apparently `oda_api` version in submodule reference could not be merged with master.

And it was strange, because it didn't seem to be divergent. But ok. Let's observe a bit how it works with forced master and add a push-back action then.
