### ISSUE TITLE
Container image doesn't get updated on plugin change

### ISSUE THREAD

**Issue by dsavchenko** [oda-hub/dispatcher-container#6]
At least dispatcher-plugin-nb2workflow didn't trigger container update

**Comment by dsavchenko** [comment]
@volodymyrss the dispatcher container was not rebuilt after merging PR to the dispatcher-app on Sunday and yesterday's merging of PR to the plugin. Probably you could tweak the build?

**Comment by volodymyrss** [comment]
the build is triggered by the same oda-bot and sometimes it looses connection.

the container build is site-specific since we originally wanted to have separate containers for different sites, with different plugins.

but since you are using unige-built images we can just make at least one default image in this repository here. triggers since can be done in a similar way to https://github.com/oda-hub/oda-bot/issues/16 but it can be done without any extra service, will see. a service is useful for other things though, so maybe it's not bad to keep it. 

the build is starting but having some issues with diskpressure. It should complete soon.

**Comment by dsavchenko** [comment]
> the container build is site-specific since we originally wanted to have separate containers for different sites, with different plugins.

As we already have a mechanism to disable dispatcher plugins, the same containers can be used most of the time

**Comment by volodymyrss** [comment]
Dispatcher container is quite big which is a limiting factor in the deployment. One of the ways to reduce it is to have less plugins to have less dependencies. But for now it does not matter because of who uses it.
